name: Autograding Tests
"on":
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Test 01 calcular promedio 8h CO
        id: test-calcular-promedio-8h-co
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "calcular promedio 8h CO"
          command: "uv run pytest 98-tests/test_mean_8h_co.py -v"
          timeout: 2
          max-score: 30

      - name: Test 02 calcular promedio movil ponderado
        id: test-calcular-promedio-movil-ponderado
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "calcular promedio movil ponderado"
          command: "uv run pytest 98-tests/test_calcular_promedio_movil_ponderado.py -v"
          timeout: 2
          max-score: 30

      - name: Test 03 asigna indice aire salud
        id: test-asigna-indice-aire-salud
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "asigna indice aire salud"
          command: "uv run pytest 98-tests/test_asigna_indice_aire_salud.py -v"
          timeout: 2
          max-score: 30

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST-01-calcular-promedio-8h-co_RESULTS: "${{steps.test-calcular-promedio-8h-co.outputs.result}}"
          TEST-02-calcular-promedio-movil-ponderado_RESULTS: "${{steps.test-calcular-promedio-movil-ponderado.outputs.result}}"
          TEST-03-asigna-indice-aire-salud_RESULTS: "${{steps.test-asigna-indice-aire-salud.outputs.result}}"
        with:
          runners: |
            test-01-calcular-promedio-8h-co,
            test-02-calcular-promedio-movil-ponderado,
            test-03-asigna-indice-aire-salud
